### ISSUE TITLE
OSError exception in mangarock provider

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#103]
Tried with manga-py version `1.3.22`:

~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp --destination Manga/ https://mangarock.com/manga/mrs-serie-100135379

100% (18 of 18) |##########################| Elapsed Time: 0:00:47 Time:  0:00:47
N/A% (0 of 6) |                            | Elapsed Time: 0:00:00 ETA:  --:--:--Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/providers/mangarock_com.py", line 54, in save_file
    return super().save_file(idx, callback, _url, in_arc_name)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/provider.py", line 148, in save_file
    self._archive.lazy_add(_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/base_classes/archive.py", line 81, in lazy_add
    Image(_path).convert(jpeg_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/image.py", line 19, in __init__
    self.__open(src_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/image.py", line 35, in __open
    self._image = PilImage.open(_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/PIL/Image.py", line 2622, in open
    % (filename if filename else fp))
OSError: cannot identify image file '/tmp/.PyMangaDownloader/temp_13024/000.mri'

Exception in thread Thread-20:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/providers/mangarock_com.py", line 54, in save_file
    return super().save_file(idx, callback, _url, in_arc_name)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/provider.py", line 148, in save_file
    self._archive.lazy_add(_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/base_classes/archive.py", line 81, in lazy_add
    Image(_path).convert(jpeg_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/image.py", line 19, in __init__
    self.__open(src_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/image.py", line 35, in __open
    self._image = PilImage.open(_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/PIL/Image.py", line 2622, in open
    % (filename if filename else fp))
OSError: cannot identify image file '/tmp/.PyMangaDownloader/temp_13024/001.mri'

...
~~~

**Comment by 1271** [comment]
Try `1.3.23`
It works for me.

**Comment by gromenauer** [comment]
Testing in `1.3.23`:

* :ballot_box_with_check: Without `--no-webp` it's OK:
~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --destination /tmp https://mangarock.com/manga/mrs-serie-100135379 -c 3
~~~
* :boom: With `--no-webp` fails:
~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --destination /tmp https://mangarock.com/manga/mrs-serie-100135379 -c 3 --no-webp
~~~
<details>
<summary>Same output error (Click to view)</summary>

~~~
100% (18 of 18) |####################################################################################################################################################| Elapsed Time: 0:00:48 ETA:  00:00:00Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/providers/mangarock_com.py", line 54, in save_file
    return super().save_file(idx, callback, _url, in_arc_name)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/provider.py", line 152, in save_file
    self._archive.lazy_add(_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/base_classes/archive.py", line 81, in lazy_add
    Image(_path).convert(jpeg_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/image.py", line 19, in __init__
    self.__open(src_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/image.py", line 35, in __open
    self._image = PilImage.open(_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/PIL/Image.py", line 2622, in open
    % (filename if filename else fp))
OSError: cannot identify image file '/tmp/.PyMangaDownloader/temp_8235/000.mri'

Exception in thread Thread-20:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/providers/mangarock_com.py", line 54, in save_file
    return super().save_file(idx, callback, _url, in_arc_name)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/provider.py", line 152, in save_file
    self._archive.lazy_add(_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/base_classes/archive.py", line 81, in lazy_add
    Image(_path).convert(jpeg_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/image.py", line 19, in __init__
    self.__open(src_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/image.py", line 35, in __open
    self._image = PilImage.open(_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/PIL/Image.py", line 2622, in open
    % (filename if filename else fp))
OSError: cannot identify image file '/tmp/.PyMangaDownloader/temp_8235/001.mri'

Exception in thread Thread-21:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/providers/mangarock_com.py", line 54, in save_file
    return super().save_file(idx, callback, _url, in_arc_name)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/provider.py", line 152, in save_file
    self._archive.lazy_add(_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/base_classes/archive.py", line 81, in lazy_add
    Image(_path).convert(jpeg_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/image.py", line 19, in __init__
    self.__open(src_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/image.py", line 35, in __open
    self._image = PilImage.open(_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/PIL/Image.py", line 2622, in open
    % (filename if filename else fp))
OSError: cannot identify image file '/tmp/.PyMangaDownloader/temp_8235/002.mri'

Exception in thread Thread-22:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/providers/mangarock_com.py", line 54, in save_file
    return super().save_file(idx, callback, _url, in_arc_name)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/provider.py", line 152, in save_file
    self._archive.lazy_add(_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/base_classes/archive.py", line 81, in lazy_add
    Image(_path).convert(jpeg_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/image.py", line 19, in __init__
    self.__open(src_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/image.py", line 35, in __open
    self._image = PilImage.open(_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/PIL/Image.py", line 2622, in open
    % (filename if filename else fp))
OSError: cannot identify image file '/tmp/.PyMangaDownloader/temp_8235/003.mri'

Exception in thread Thread-24:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/providers/mangarock_com.py", line 54, in save_file
    return super().save_file(idx, callback, _url, in_arc_name)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/provider.py", line 152, in save_file
    self._archive.lazy_add(_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/base_classes/archive.py", line 81, in lazy_add
    Image(_path).convert(jpeg_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/image.py", line 19, in __init__
    self.__open(src_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/image.py", line 35, in __open
    self._image = PilImage.open(_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/PIL/Image.py", line 2622, in open
    % (filename if filename else fp))
OSError: cannot identify image file '/tmp/.PyMangaDownloader/temp_8235/005.mri'

Exception in thread Thread-23:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/providers/mangarock_com.py", line 54, in save_file
    return super().save_file(idx, callback, _url, in_arc_name)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/provider.py", line 152, in save_file
    self._archive.lazy_add(_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/base_classes/archive.py", line 81, in lazy_add
    Image(_path).convert(jpeg_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/image.py", line 19, in __init__
    self.__open(src_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/image.py", line 35, in __open
    self._image = PilImage.open(_path)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/PIL/Image.py", line 2622, in open
    % (filename if filename else fp))
OSError: cannot identify image file '/tmp/.PyMangaDownloader/temp_8235/004.mri'

100% (18 of 18) |####################################################################################################################################################| Elapsed Time: 0:00:57 Time:  0:00:57
N/A% (0 of 25) |                                                                                                                                                     | Elapsed Time: 0:00:00 ETA:  --:--:--Exception in thread Thread-25:
...
~~~
</details>

**Comment by gromenauer** [comment]
> It works for me.
Nowadays the standard answer for this is Docker.

**Comment by 1271** [comment]
`With --no-webp fails`

I'll check it on another PC. Perhaps there will be an error.

Yes, you are right at the expense of the docker, but, as I said, very few people use it. He is not comfortable.

**Comment by gromenauer** [comment]
You could check it in a docker instance ;)

The docker instance is more for testing than for normal use. If the docker instance fails I know that is the same for your docker. If my PC fails and docker instance not, then my PC it's the one to blame (or should be).

**Comment by 1271** [comment]
I did it! Now it works well!

It works on all my PCs.
I checked it even on the server :-)

---

As for the Docker container. Perhaps this will make sense for version 2.0, so that there are no such situations.
Thanks, I'll think about it in the future :-)

**Comment by gromenauer** [comment]
Works OK in manga-py version `1.3.24` :+1:
