### ISSUE TITLE
Request to add a site: comicpunch

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#168]
# Request to add a site

Description | Data
---|---
Url to add | `https://comicpunch.net/amazing-spider-man-2018`

**Comment by 1271** [comment]
Please check for updates :-)

**Comment by gromenauer** [comment]
Works, seems to fail, but with a strange one page last chapter.

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.5.6.1
URL | `https://comicpunch.net/amazing-spider-man-2018`

~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp --show-current-chapter-info --destination Manga/ https://comicpunch.net/amazing-spider-man-2018
~~~

~~~
...
Current chapter url: https://comicpunch.net/reader/Amazing-Spider+Man-2018/Amazing-Spider-Man-(2018)-Issue-23

Error processing file: vol_Issue-23
100% (33 of 33) |####################################################################################################################################################| Elapsed Time: 0:00:05 Time:  0:00:05


Error processing file: vol_Issue-23
~~~

**Comment by gromenauer** [comment]
:bug: Tried (but failed :boom:):

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.5.6.1
URL | `https://comicpunch.net/delver`


~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp --show-current-chapter-info --destination Manga/ https://comicpunch.net/delver
~~~
~~~ py
2019-06-02 10:34:22.558 | ERROR    | manga_py.cli:start:41 - An error has been caught in function 'start', process 'MainProcess' (9396), thread 'MainThread' (140267531392768):
Traceback (most recent call last):

  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/bin/manga-py", line 10, in <module>
    sys.exit(main())
    │   │    └ <function main at 0x7f9292939048>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/__init__.py", line 92, in main
    code, _info = _run_util(args)
                  │         └ ArgumentParser(prog='manga-py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler...
                  └ <function _run_util at 0x7f9292927e18>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/__init__.py", line 51, in _run_util
    code = _init_cli(args, _info)
           │         │     └ <manga_py.info.Info object at 0x7f929293b7b8>
           │         └ ArgumentParser(prog='manga-py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler...
           └ <function _init_cli at 0x7f9292927d90>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/__init__.py", line 39, in _init_cli
    cli_mode.start()
    │        └ <bound method Cli.start of <manga_py.cli.Cli object at 0x7f929293b6d8>>
    └ <manga_py.cli.Cli object at 0x7f929293b6d8>
> File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/cli/__init__.py", line 41, in start
    self.parser.start()
    │    │      └ <bound method Parser.start of <manga_py.parser.Parser object at 0x7f929293b7f0>>
    │    └ <manga_py.parser.Parser object at 0x7f929293b7f0>
    └ <manga_py.cli.Cli object at 0x7f929293b6d8>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/parser.py", line 45, in start
    self.provider.process(self.params['url'], self.params)
    │    │        │       │    │              │    └ {'skip_volumes': 0, 'show_current_chapter_info': True, 'min_free_space': 100, 'with_manga_name': False, 'max_volumes': 0, 'desti...
    │    │        │       │    │              └ <manga_py.parser.Parser object at 0x7f929293b7f0>
    │    │        │       │    └ {'skip_volumes': 0, 'show_current_chapter_info': True, 'min_free_space': 100, 'with_manga_name': False, 'max_volumes': 0, 'desti...
    │    │        │       └ <manga_py.parser.Parser object at 0x7f929293b7f0>
    │    │        └ <bound method Provider.process of <manga_py.providers.comicpunch_net.ComicPunchNet object at 0x7f929293b908>>
    │    └ <manga_py.providers.comicpunch_net.ComicPunchNet object at 0x7f929293b908>
    └ <manga_py.parser.Parser object at 0x7f929293b7f0>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/provider.py", line 83, in process
    self.loop_chapters()
    │    └ <bound method Provider.loop_chapters of <manga_py.providers.comicpunch_net.ComicPunchNet object at 0x7f929293b908>>
    └ <manga_py.providers.comicpunch_net.ComicPunchNet object at 0x7f929293b908>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/provider.py", line 114, in loop_chapters
    self._info.add_volume(self.chapter_for_json(), self.get_archive_path())
    │    │     │          │    │                   │    └ <bound method Provider.get_archive_path of <manga_py.providers.comicpunch_net.ComicPunchNet object at 0x7f929293b908>>
    │    │     │          │    │                   └ <manga_py.providers.comicpunch_net.ComicPunchNet object at 0x7f929293b908>
    │    │     │          │    └ <bound method Base.chapter_for_json of <manga_py.providers.comicpunch_net.ComicPunchNet object at 0x7f929293b908>>
    │    │     │          └ <manga_py.providers.comicpunch_net.ComicPunchNet object at 0x7f929293b908>
    │    │     └ <bound method Info.add_volume of <manga_py.info.Info object at 0x7f929293b7b8>>
    │    └ <manga_py.info.Info object at 0x7f929293b7b8>
    └ <manga_py.providers.comicpunch_net.ComicPunchNet object at 0x7f929293b908>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/provider.py", line 163, in get_archive_path
    _path = remove_file_query_params(self.get_archive_name())
            │                        │    └ <bound method Std.get_archive_name of <manga_py.providers.comicpunch_net.ComicPunchNet object at 0x7f929293b908>>
            │                        └ <manga_py.providers.comicpunch_net.ComicPunchNet object at 0x7f929293b908>
            └ <function remove_file_query_params at 0x7f92929230d0>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/providers/helpers/std.py", line 5, in get_archive_name
    idx = self.get_chapter_index()
          │    └ <bound method ComicPunchNet.get_chapter_index of <manga_py.providers.comicpunch_net.ComicPunchNet object at 0x7f929293b908>>
          └ <manga_py.providers.comicpunch_net.ComicPunchNet object at 0x7f929293b908>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/providers/comicpunch_net.py", line 9, in get_chapter_index
    return self.re.search(r'-((?:Annual|Issue)-\w+)', self.chapter).group(1)
           │    │  │                                  │    └ 'https://comicpunch.net/reader/Delver/Delver-(2019)-Chapter-1'
           │    │  │                                  └ <manga_py.providers.comicpunch_net.ComicPunchNet object at 0x7f929293b908>
           │    │  └ <function search at 0x7f9292d51d08>
           │    └ <module 're' from '~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/re.py'>
           └ <manga_py.providers.comicpunch_net.ComicPunchNet object at 0x7f929293b908>

AttributeError: 'NoneType' object has no attribute 'group'
~~~

**Comment by 1271** [comment]
Sorry .... -_-
I'll check it out.

**Comment by gromenauer** [comment]
Don't be sorry, you have done more than we paid for :innocent:

**Comment by gromenauer** [comment]
Works OK
~~~
https://comicpunch.net/unearthmanga-user@074f07530072:/home/manga$ manga-py https://comicpunch.net/delver -c 2
100% (34 of 34) |####################################################################################################################################################| Elapsed Time: 0:00:18 Time:  0:00:18
100% (27 of 27) |####################################################################################################################################################| Elapsed Time: 0:00:11 Time:  0:00:11
~~~
But seems that last chapter could be a fake one (to click bait):
~~~
manga-user@074f07530072:/home/manga$ manga-py https://comicpunch.net/unearth -c  1
 96% (28 of 29) |##############################################################################################################################################      | Elapsed Time: 0:00:09 ETA:   0:00:00

manga-user@074f07530072:/home/manga$ manga-py https://comicpunch.net/delver -c 1 --reverse-downloading
Error processing file: vol_Chapter-5
 
manga-user@074f07530072:/home/manga$ manga-py https://comicpunch.net/unearth -c 1 --reverse-downloading
Error processing file: vol_Issue-2
~~~


Could be this fake chapter detected? If so, then reopen the issue to improve on this.

**Comment by 1271** [comment]
I do not know whether it will work. But I'll try

https://comicpunch.net/reader/Delver/Delver-(2019)-Chapter-5/?q=fullchapter

The problem is that when you turn on the "list mode", the first image disappears. And since there is only one picture, manga-py does not see the files.
Because of this, an error occurs.

**Comment by 1271** [comment]
![PrtScr](https://user-images.githubusercontent.com/1452243/61104772-35fc3100-a480-11e9-9ba7-54828cadea2e.png)
Oh ... I was wrong. There are no images at all :-(
