### ISSUE TITLE
Bug mangadex

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#171]
# Bug report
Environment:

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.0.3 
Npm version | 3.5.2
Manga-py version | 1.5.4
URL | `https://mangadex.org/title/35064/im-a-villainous-daughter-so-im-going-to-keep-the-last-boss`

#### To Reproduce:

~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp --destination Manga/ \
  --name "i_m_a_villainous_daughter_so_i_m_going_to_keep_the_last_boss" \
  "https://mangadex.org/title/35064/im-a-villainous-daughter-so-im-going-to-keep-the-last-boss" 
~~~

#### Additional context
~~~
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/parser.py", line 42, in start
    self.provider.process(self.params['url'], self.params)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/provider.py", line 71, in process
    self._storage['manga_name'] = self.get_manga_name()
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/providers/mangadex_com.py", line 39, in get_manga_name
    name = self.html_fromstring(url, '.card-header', 0).text_content()
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/provider.py", line 211, in html_fromstring
    return self.document_fromstring(self.http_get(url, **params), selector, idx)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/base_classes/static.py", line 24, in document_fromstring
    result = result[idx]
~~~

**Comment by 1271** [comment]
Hmmm...
I don't see this error for me :(
Please, show this source for you browser:
```
view-source:https://mangadex.org/title/35064/im-a-villainous-daughter-so-im-going-to-keep-the-last-boss
```
This node exists?
![изображение](https://user-images.githubusercontent.com/1452243/56356374-62861100-61e1-11e9-85db-57895e486f6b.png)

**Comment by gromenauer** [comment]
Seems that with `view-source:https://mangadex.org/title/35064/im-a-villainous-daughter-so-im-going-to-keep-the-last-boss` I get the same.

~~~ html
<div class="card mb-3">
<h6 class="card-header d-flex align-items-center py-2">
<span class='fas fa-book fa-fw ' aria-hidden='true'></span> <span class="mx-1">I'm a Villainous Daughter, so I'm going to keep the Last Boss</span>
<span class='rounded flag flag-jp' title='Japanese'></span> <span class="ml-1"></span>
~~~
Tried with `wget https://mangadex.org/title/35064/im-a-villainous-daughter-so-im-going-to-keep-the-last-boss -O - | less`

~~~ html
<div class="card mb-3">
<h6 class="card-header d-flex align-items-center py-2">
<span class='fas fa-book fa-fw ' aria-hidden='true'></span> <span class="mx-1">I'm a Villainous Daughter, so I'm going to keep the Last Boss</span>
<span class='rounded flag flag-jp' title='Japanese'></span> <span class="ml-1"></span>
~~~

**Comment by gromenauer** [comment]
Reinstalled `manga-py` and everything worked :sweat_smile:

**Comment by gromenauer** [comment]
Is `https://kissmanga.com/Manga/The-Hero-is-Overpowered-but-Overly-Cautious` working for you?

**Comment by 1271** [comment]
> Maybe it's my fault (Npm version 3.5.2) but I have a very strange error

No. This is not your mistake.
Unfortunately, this is currently broken for all sites protected by cloudflate (see https://github.com/Anorov/cloudflare-scrape/issues)

**Comment by gromenauer** [comment]
Same bug again. 

Maybe they are banning crawlers?
~~~ bash
LANG= wget https://mangadex.org/title/28558/versatile-mage
--2019-04-19 09:42:27--  https://mangadex.org/title/28558/versatile-mage
~~~
~~~
Resolving mangadex.org (mangadex.org)... 104.20.7.190, 104.20.8.190, 2606:4700:10::6814:7be, ...
Connecting to mangadex.org (mangadex.org)|104.20.7.190|:443... connected.
HTTP request sent, awaiting response... 503 Service Temporarily Unavailable
2019-04-19 09:42:27 ERROR 503: Service Temporarily Unavailable.
~~~

In firefox I see:
~~~ html
<div class="card mb-3">
<h6 class="card-header d-flex align-items-center py-2">
<span class='fas fa-book fa-fw ' aria-hidden='true'></span> <span class="mx-1">Versatile Mage</span>
~~~

Using  #177 I have a more detailed log:

~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp   --destination Manga/ --name "m_versatile_mage"   "https://mangadex.org/title/28558/versatile-mage" 
~~~
~~~
2019-04-19 09:10:50.675 | ERROR    | manga_py.cli:start:45 - An error has been caught in function 'start', process 'MainProcess' (13230), thread 'MainThread' (140346428143360):
Traceback (most recent call last):

  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/bin/manga-py", line 10, in <module>
    sys.exit(main())
    │   │    └ <function main at 0x7fa4eef326a8>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/__init__.py", line 91, in main
    code, _info = _run_util(args)
                  │         └ ArgumentParser(prog='manga-py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler...
                  └ <function _run_util at 0x7fa4eef32510>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/__init__.py", line 51, in _run_util
    code = _init_cli(args, _info)
           │         │     └ <manga_py.info.Info object at 0x7fa4eef5b828>
           │         └ ArgumentParser(prog='manga-py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler...
           └ <function _init_cli at 0x7fa4eef32488>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/__init__.py", line 39, in _init_cli
    cli_mode.start()
    │        └ <bound method Cli.start of <manga_py.cli.Cli object at 0x7fa4eef5b7b8>>
    └ <manga_py.cli.Cli object at 0x7fa4eef5b7b8>
> File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/cli/__init__.py", line 45, in start
    self.parser.start()
    │    │      └ <bound method Parser.start of <manga_py.parser.Parser object at 0x7fa4eef5b6d8>>
    │    └ <manga_py.parser.Parser object at 0x7fa4eef5b6d8>
    └ <manga_py.cli.Cli object at 0x7fa4eef5b7b8>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/parser.py", line 44, in start
    self.provider.process(self.params['url'], self.params)
    │    │        │       │    │              │    └ {'max_volumes': 0, 'no_progress': False, 'reverse_downloading': False, 'rename_pages': True, 'no_multi_threads': False, 'print_j...
    │    │        │       │    │              └ <manga_py.parser.Parser object at 0x7fa4eef5b6d8>
    │    │        │       │    └ {'max_volumes': 0, 'no_progress': False, 'reverse_downloading': False, 'rename_pages': True, 'no_multi_threads': False, 'print_j...
    │    │        │       └ <manga_py.parser.Parser object at 0x7fa4eef5b6d8>
    │    │        └ <bound method Provider.process of <manga_py.providers.mangadex_com.MangaDexCom object at 0x7fa4eef5ba58>>
    │    └ <manga_py.providers.mangadex_com.MangaDexCom object at 0x7fa4eef5ba58>
    └ <manga_py.parser.Parser object at 0x7fa4eef5b6d8>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/provider.py", line 71, in process
    self._storage['manga_name'] = self.get_manga_name()
    │    │                        │    └ <bound method MangaDexCom.get_manga_name of <manga_py.providers.mangadex_com.MangaDexCom object at 0x7fa4eef5ba58>>
    │    │                        └ <manga_py.providers.mangadex_com.MangaDexCom object at 0x7fa4eef5ba58>
    │    └ {'proxies': {}, 'current_file': 0, 'main_content': None, 'current_chapter': 0, 'domain_uri': 'https://mangadex.org', 'cookies': ...
    └ <manga_py.providers.mangadex_com.MangaDexCom object at 0x7fa4eef5ba58>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/providers/mangadex_com.py", line 39, in get_manga_name
    name = self.html_fromstring(url, '.card-header', 0).text_content()
           │    │               └ 'https://mangadex.org/title/28558/versatile-mage'
           │    └ <bound method Provider.html_fromstring of <manga_py.providers.mangadex_com.MangaDexCom object at 0x7fa4eef5ba58>>
           └ <manga_py.providers.mangadex_com.MangaDexCom object at 0x7fa4eef5ba58>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/provider.py", line 211, in html_fromstring
    return self.document_fromstring(self.http_get(url, **params), selector, idx)
           │    │                   │    │        │      │        │         └ 0
           │    │                   │    │        │      │        └ '.card-header'
           │    │                   │    │        │      └ {}
           │    │                   │    │        └ 'https://mangadex.org/title/28558/versatile-mage'
           │    │                   │    └ <bound method Base.http_get of <manga_py.providers.mangadex_com.MangaDexCom object at 0x7fa4eef5ba58>>
           │    │                   └ <manga_py.providers.mangadex_com.MangaDexCom object at 0x7fa4eef5ba58>
           │    └ <function Static.document_fromstring at 0x7fa4ed43f378>
           └ <manga_py.providers.mangadex_com.MangaDexCom object at 0x7fa4eef5ba58>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/base_classes/static.py", line 24, in document_fromstring
    result = result[idx]
    │        │      └ 0
    │        └ []
    └ []

IndexError: list index out of range
~~~

**Comment by 1271** [comment]
O!!!
_2019-04-19 09:42:27 ERROR 503: Service Temporarily Unavailable._

Their website is sometimes unavailable.
This may be due to errors of the site itself.
I think if they somehow understood that manga-py is a crawler, they would block it altogether.
You can try changing the behavior of manga-py a bit by installing your user-agent:
`--user-agent`
https://github.com/yuru-yuri/manga-dl/blob/stable_1.x/manga_py/cli/args.py#L52

**Comment by 1271** [comment]
I am also confused by the error
IndexError: list index out of range
I'll look into it after work. Thank

**Comment by gromenauer** [comment]
Will do. 
It works randomly (now works), maybe they are A/B testing something.

**Comment by gromenauer** [comment]
Feel free to close #177, it's more a example than a proper pull request.

**Comment by paulolimac** [comment]
Hello guys!

I reproduced the first bug.

### My setup

OS: Ubuntu 18.04
Python: 3.6.7
Pip: 9.1.0
Pip-modules:
```
$pipdeptree
manga-py==1.5.4
  - cfscrape [required: Any, installed: 1.9.7]
    - requests [required: >=2.0.0, installed: 2.21.0]
      - certifi [required: >=2017.4.17, installed: 2019.3.9]
      - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
      - idna [required: >=2.5,<2.9, installed: 2.8]
      - urllib3 [required: >=1.21.1,<1.25, installed: 1.24.3]
  - cssselect [required: Any, installed: 1.0.3]
  - html-purifier [required: Any, installed: 0.1.9]
  - lxml [required: Any, installed: 4.3.3]
  - packaging [required: Any, installed: 19.0]
    - pyparsing [required: >=2.0.2, installed: 2.4.0]
    - six [required: Any, installed: 1.12.0]
  - Pillow [required: Any, installed: 6.0.0]
  - progressbar2 [required: Any, installed: 3.39.3]
    - python-utils [required: >=2.3.0, installed: 2.3.0]
      - six [required: Any, installed: 1.12.0]
    - six [required: Any, installed: 1.12.0]
  - pycrypto [required: Any, installed: 2.6.1]
  - pyexecjs [required: >=1.5.1, installed: 1.5.1]
    - six [required: >=1.10.0, installed: 1.12.0]
  - requests [required: Any, installed: 2.21.0]
    - certifi [required: >=2017.4.17, installed: 2019.3.9]
    - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
    - idna [required: >=2.5,<2.9, installed: 2.8]
    - urllib3 [required: >=1.21.1,<1.25, installed: 1.24.3]
  - urllib3 [required: Any, installed: 1.24.3]
```

I get a version conflict between `requests` and `urllib3`. The last one I downgraded to run the `manga-py`.

### Running

I tried 3-4 different manga pages from `mangadex.org`, but without success.
And I tried 2 other manga pages from different sites (`sensescans` and `mangakalot`), with success.
So, my web-conection works, my instance of manga-py works, and the problem is isolated/specific at `mangadex.org` submodule.

My firefox show me the h6 tag too:
```
<div class="card mb-3">
<h6 class="card-header d-flex align-items-center py-2">
<span class='fas fa-book fa-fw ' aria-hidden='true'></span> <span class="mx-1">I'm a Villainous Daughter, so I'm going to keep the Last Boss</span>
```

### Example

Reproducing the bug:
```
$ manga-py https://mangadex.org/title/9530/high-score-girl
  File "/home/user/Downloads/manga/hi_score_girl/my_env/lib/python3.6/site-packages/manga_py/parser.py", line 42, in start
    self.provider.process(self.params['url'], self.params)
  File "/home/user/Downloads/manga/hi_score_girl/my_env/lib/python3.6/site-packages/manga_py/provider.py", line 71, in process
    self._storage['manga_name'] = self.get_manga_name()
  File "/home/user/Downloads/manga/hi_score_girl/my_env/lib/python3.6/site-packages/manga_py/providers/mangadex_com.py", line 39, in get_manga_name
    name = self.html_fromstring(url, '.card-header', 0).text_content()
  File "/home/user/Downloads/manga/hi_score_girl/my_env/lib/python3.6/site-packages/manga_py/provider.py", line 211, in html_fromstring
    return self.document_fromstring(self.http_get(url, **params), selector, idx)
  File "/home/user/Downloads/manga/hi_score_girl/my_env/lib/python3.6/site-packages/manga_py/base_classes/static.py", line 24, in document_fromstring
    result = result[idx]
```

### My two cents:

1. Is the `manga-py` parsing `mangadex.org` url correctly? Maybe:
1.1. `https://mangadex.org/title/35064/im-a-villainous-daughter-so-im-going-to-keep-the-last-boss` or
1.2. `https://mangadex.org/title/35064/im-a-villainous-daughter-so-im-going-to-keep-the-last-boss/` or
1.3. `https://mangadex.org/title/35064/` or
1.4. `https://mangadex.org/title/35064`

2. Is a status indicator in `mangadex.org` to see if the site is down? If the site accept crawlers/robots? Because in Firefox it works with no problem. Maybe running the command in a cronjob (repetitively) we can see if the problem is temporally from `mangadex`.

**Comment by 1271** [comment]
@paulolimac

Thanks for this message.
I'll check it again :)

`My two cents`
1. Its true for 1.1 and 1.2 https://github.com/yuru-yuri/manga-dl/blob/2dd8544e5fe41c23054b2c5a799892a857fceaca/manga_py/providers/mangadex_com.py#L33
2. Unfortunately, this is not possible now. Logging will be in version 2.0 (which I still can’t do anyway :disappointed:)
