### ISSUE TITLE
Bug: heavenmanga.biz

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#173]
# Bug report

Just exploring for new content (I'm not waiting on this, just reporting) I have stumbled in this, it seems a "too many chapters" bug.

Environment:

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.0.3 
Npm version | 3.5.2
Manga-py version | 1.5.4
URL | `http://heavenmanga.biz/denma/`

#### To Reproduce:

~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages \
  --no-webp --destination Manga/ \
  http://heavenmanga.biz/denma/ --print-json --simulate
~~~

#### Additional context

~~~
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/provider.py", line 81, in process
    self.loop_chapters()
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/provider.py", line 112, in loop_chapters
    self._info.add_volume(self.chapter_for_json(), self.get_archive_path())
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/provider.py", line 159, in get_archive_path
    _path = remove_file_query_params(self.get_archive_name())
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/providers/helpers/std.py", line 8, in get_archive_name
    idx = self.get_chapter_index()
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/providers/heavenmanga_biz.py", line 8, in get_chapter_index
    return self.re.search(r'-chap-(\d+(?:-\d+)?)', self.chapter).group(1)
Traceback (most recent call last):
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/bin/manga-py", line 10, in <module>
    sys.exit(main())
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/__init__.py", line 90, in main
    code, _info = _run_util(args)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/__init__.py", line 57, in _run_util
    sort_keys=True,
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 200, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.5/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: AttributeError("'NoneType' object has no attribute 'group'",) is not JSON serializable
~~~

**Comment by 1271** [comment]
Not really. Problem in this chapter
It does not fall under the regular expression.
It works now. thank
![изображение](https://user-images.githubusercontent.com/1452243/57568096-632e5380-73eb-11e9-8863-00db252d9e24.png)

---

There is another problem with this manga.
Chapters 1.2 and 12 have the same address :-(
Unfortunately, it is impossible to fix this on our part. Need to write site administration

**Comment by gromenauer** [comment]
:bug: Seems to download it, but all the pages are the same banner:

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.5.5.1
URL | `http://heavenmanga.biz/denma/`

**Comment by 1271** [comment]
Oh.. You right.. Sorry.
I will fix it after my work

**Comment by 1271** [comment]
> all the pages are the same banner

Oh. I forgot this issue
But as I see it, the problem is not relevant now (it works well for me)

**Comment by gromenauer** [comment]
Works OK with `.vip` domain

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.5.6.1
URL | `http://heavenmanga.vip/denma/` :+1: 
URL | `http://heavenmanga.biz/denma/` :bug: :boom: 

:bug: With  `.biz` domain seems to download it, but all the pages are the same banner

**Comment by 1271** [comment]
Heh. I could not get to the .biz domain, I automatically redirect to .vip

**Comment by gromenauer** [comment]
OK. Works for this case (Except when you get the URL from `info.txt` in an old comic).

But, please consider create a function for rewriting internally the url parameter. In this case when the user asks for `params['url']='http://heavenmanga.biz/denma/'` then the script substitutes it by `params['url']='http://heavenmanga.vip/denma/'`. Then faulty web server redirections are easily avoided.
