### ISSUE TITLE
Request to add a site: viz.com/shonenjump

### ISSUE THREAD

**Issue by mugenZebra** [yuru-yuri/manga-dl#184]
# Request to add a site

Description | Data
---|---
Url to add | https://www.viz.com/shonenjump/chapters

**Comment by mugenZebra** [comment]
I tried the 0.x executable, but it didn't download and closed the terminal immediately. I am subscribed to viz's shonen jump, I would also like to request a feature to login with my account when downloading. Thanks.

**Comment by 1271** [comment]
OK. I will try to do it.

Version 0.x is not supported now. The executable file is working, but it needs to be called from the command line. It does not have a GUI.

**Comment by 1271** [comment]
So. About viz
It's complicated -_-
The fact is that I need an account to see what it looks like on behalf of a registered user (or at least page dumps)
In addition, unfortunately, the site is not available in my country (I use vpn in Italy and the United States to fix it, but it does not always help -_-)

May I ask you to send an archive with pages?

Looking for the following data:
1. A page with a list of chapters (preferably with a manga, where there is a paginator, if it is used on this site)
2. Page with pictures

You can save simply through CTRL + S

---
I hope you understand me. Sorry for my English :-(

**Comment by mugenZebra** [comment]
There are free access to the latest few chapters. Just for example:
1. https://www.viz.com/shonenjump/chapters/dr-stone
2. https://www.viz.com/shonenjump/dr-stone-chapter-106/chapter/18224?action=read

So the images are obfuscated for copyright protection, like [this](https://i.imgur.com/FlxaKz6.jpg).

**Comment by 1271** [comment]
> images are obfuscated

its not problem

Thx for snapshots. I'll do this a little later.

**Comment by 1271** [comment]
For several reasons, work on the provider for viz is delayed. Sorry

**Comment by 1271** [comment]
First step result. yay!
![index3](https://user-images.githubusercontent.com/1452243/61631692-b1858b80-ac93-11e9-934b-b8923f5437f4.jpeg)

**Comment by 1271** [comment]
And ... Done!
It really works!

After about 4-5 hours there will be a release.

**Comment by 1271** [comment]
Phew It was complicated )
Done!
Unfortunately, it works ... strange
The number of images will temporarily show 250
But do not worry. Only those that are in the manga should be archived.

Please check it.
It was really difficult for me to work with this site, because it is not accessible from Russia :-(

Anyway. If he works for you, I will be glad
If you have any difficulties, feel free to write
If it works, please wait a little longer. I will try to correct this oddity with the number of pages.

--- 
P.S.
If you leave the login or password field blank, the provider will be started in guest mode

**Comment by gromenauer** [comment]
Fails gracefully out of USA and Japan. (Works as intended)

~~~
...
Try to get free chapters...
Warning! This site worked from USA and Japan! Check your location
~~~

**Comment by 1271** [comment]
@gromenauer yes, that's right.
Unfortunately, I can check only Russia, Italy and the USA (maybe it works in some other countries. Not sure)

**Comment by mugenZebra** [comment]
> 
> 
> Phew It was complicated )
> Done!
> Unfortunately, it works ... strange
> The number of images will temporarily show 250
> But do not worry. Only those that are in the manga should be archived.
> 
> Please check it.
> It was really difficult for me to work with this site, because it is not accessible from Russia :-(
> 
> Anyway. If he works for you, I will be glad
> If you have any difficulties, feel free to write
> If it works, please wait a little longer. I will try to correct this oddity with the number of pages.
> 
> P.S.
> If you leave the login or password field blank, the provider will be started in guest mode

I upgraded to version 1.8.2.2, then tried 

> (base) C:\Users\roba7\workspace\manga>manga-py https://www.viz.com/shonenjump/dr-stone-chapter-114/chapter/18621?action=read
> Provider not found
> Please check the domain in the table: https://yuru-yuri.github.io/manga-dl/
> Make sure that the URL is correct
> 
> Trace:
>   File "c:\users\roba7\anaconda3\lib\site-packages\manga_py\__init__.py", line 43, in _init_cli
>     cli_mode.start()
>   File "c:\users\roba7\anaconda3\lib\site-packages\manga_py\cli\__init__.py", line 40, in start
>     raise e
>   File "c:\users\roba7\anaconda3\lib\site-packages\manga_py\cli\__init__.py", line 34, in start
>     info=self._info,
>   File "c:\users\roba7\anaconda3\lib\site-packages\manga_py\parser.py", line 35, in init_provider
>     raise AttributeError('Provider not found')

Maybe my command is wrong? 

and somehow your provider list link is dead https://yuru-yuri.github.io/manga-dl/
Thanks for all the work, and keep it up.

**Comment by mugenZebra** [comment]
Ok I figured out. The command should be like "manga-py https://www.viz.com/shonenjump/chapters/dr-stone" So it turns out that it works and the image downloaded aren't obfuscated, but even with my paid membership, I'm getting only the free chapters, that are first three and last three chapters.

**Comment by 1271** [comment]
@mugenZebra thanks for the information
Can you send a page with a list of chapters?
(CTRL + S in your browser)

Maybe I get the wrong list of chapters.

P.S.
About the link. I changed the name of the repository a bit so that there was less confusion
See here: https://yuru-yuri.github.io/manga-py

P.P.S.
Oh. Thank. I forgot to change the hint link for manga-py

**Comment by 1271** [comment]
Hi :hand:. If you are still interested in this issue, please send the archive with the page here (github allows you to attach archives to the answer).

Thank.

**Comment by mugenZebra** [comment]
> 
> 
> @mugenZebra thanks for the information
> Can you send a page with a list of chapters?
> (CTRL + S in your browser)
> 
> Maybe I get the wrong list of chapters.
> 
> P.S.
> About the link. I changed the name of the repository a bit so that there was less confusion
> See here: https://yuru-yuri.github.io/manga-py
> 
> P.P.S.
> Oh. Thank. I forgot to change the hint link for manga-py

sorry for the late reply. Here's another snapshot saved with Firefox. Thanks for working on it.
https://file.io/fRKvro

**Comment by 1271** [comment]
> https://file.io/fRKvro

404 Not Found

Please use github. It allows you to attach files to the response. ([empty.zip](https://github.com/yuru-yuri/manga-py/files/3475663/empty.zip))
The first time you sent the link, it didn’t work either. :-(

**Comment by mugenZebra** [comment]
[shonenJumpviz.zip](https://github.com/yuru-yuri/manga-py/files/3479191/shonenJumpviz.zip)
Great, didn't know that.

**Comment by 1271** [comment]
Oh!  I understood my mistake. Thank!

... or not ...

Please, install this:
```
pip install manga-py==1.8.3.1rc1
```
This version will sprinkle with logs.
Please send logs here.

Run this as:
```
manga-py https://www.viz.com/shonenjump/chapters/dr-stone -np --debug
```

**Comment by 1271** [comment]
P.S. in the directory from which manga-py will be launched, the debug-viz directory will be created.
Please send her too.

To get the log to the file, you can use the command **`>`**
eg:

`manga-py example.org > file.log`

Thanks.

**Comment by mugenZebra** [comment]
Hi sorry for the late reply, didn't see it until now. Here's the log.
[log.log](https://github.com/yuru-yuri/manga-py/files/3524599/log.log)
And the viz_debug file:

[chapter_5558_page_0.txt](https://github.com/yuru-yuri/manga-py/files/3524604/chapter_5558_page_0.txt)
it's supposed to be .html but github doesn't let me upload it so I changed the extension.

**Comment by 1271** [comment]
Please make an archive for the debug-viz directory

Or was there only 1 file of zero size?

---

Ok... Try it

```
pip install manga-py==1.8.4rc2
```

Run:

```
manga-py https://www.viz.com/shonenjump/chapters/dr-stone -np --debug > debug.log
```

Please also attach the archive with the viz_debug directory

thanks

**Comment by mugenZebra** [comment]
Hi,

I tried, here's the generated files. 
[Manga.zip](https://github.com/manga-py/manga-py/files/3598848/Manga.zip)

I also got this error message in the commandline:

> 
> 2019-09-10 21:20:30.211 | ERROR    | manga_py.cli:start:41 - An error has been caught in function 'start', process 'MainProcess' (7616), thread 'MainThread' (7532):
> Traceback (most recent call last):
> 
>   File "c:\users\roba7\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>                 └ ModuleSpec(name='__main__', loader=<zipimporter object "C:\Users\roba7\Anaconda3\Scripts\manga-py.exe">, origin='C:\\Users\\roba...
>   File "c:\users\roba7\anaconda3\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>     │    │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "C:\Users\roba7\Anaconda3\Scripts...
>     │    └ <code object <module> at 0x0000025C42F5E930, file "C:\Users\roba7\Anaconda3\Scripts\manga-py.exe\__main__.py", line 2>
>     └ <built-in function exec>
>   File "C:\Users\roba7\Anaconda3\Scripts\manga-py.exe\__main__.py", line 9, in <module>
>   File "c:\users\roba7\anaconda3\lib\site-packages\manga_py\__init__.py", line 96, in main
>     code, _info = _run_util(args)
>                   │         └ ArgumentParser(prog='manga-py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler...
>                   └ <function _run_util at 0x0000025C436AF510>
>   File "c:\users\roba7\anaconda3\lib\site-packages\manga_py\__init__.py", line 55, in _run_util
>     code = _init_cli(args, _info)
>            │         │     └ <manga_py.info.Info object at 0x0000025C43699EF0>
>            │         └ ArgumentParser(prog='manga-py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler...
>            └ <function _init_cli at 0x0000025C436AF488>
>   File "c:\users\roba7\anaconda3\lib\site-packages\manga_py\__init__.py", line 43, in _init_cli
>     cli_mode.start()
>     │        └ <bound method Cli.start of <manga_py.cli.Cli object at 0x0000025C43699D68>>
>     └ <manga_py.cli.Cli object at 0x0000025C43699D68>
> > File "c:\users\roba7\anaconda3\lib\site-packages\manga_py\cli\__init__.py", line 41, in start
>     self.parser.start()
>     │    │      └ <bound method Parser.start of <manga_py.parser.Parser object at 0x0000025C43699E48>>
>     │    └ <manga_py.parser.Parser object at 0x0000025C43699E48>
>     └ <manga_py.cli.Cli object at 0x0000025C43699D68>
>   File "c:\users\roba7\anaconda3\lib\site-packages\manga_py\parser.py", line 45, in start
>     self.provider.process(self.params['url'], self.params)
>     │    │        │       │    │              │    └ {'url': 'https://www.viz.com/shonenjump/chapters/dr-stone', 'name': '', 'destination': 'Manga', 'no_progress': True, 'not_change...
>     │    │        │       │    │              └ <manga_py.parser.Parser object at 0x0000025C43699E48>
>     │    │        │       │    └ {'url': 'https://www.viz.com/shonenjump/chapters/dr-stone', 'name': '', 'destination': 'Manga', 'no_progress': True, 'not_change...
>     │    │        │       └ <manga_py.parser.Parser object at 0x0000025C43699E48>
>     │    │        └ <bound method Provider.process of <manga_py.providers.viz_com.VizCom object at 0x0000025C43699F28>>
>     │    └ <manga_py.providers.viz_com.VizCom object at 0x0000025C43699F28>
>     └ <manga_py.parser.Parser object at 0x0000025C43699E48>
>   File "c:\users\roba7\anaconda3\lib\site-packages\manga_py\provider.py", line 81, in process
>     self.prepare_cookies()
>     │    └ <bound method VizCom.prepare_cookies of <manga_py.providers.viz_com.VizCom object at 0x0000025C43699F28>>
>     └ <manga_py.providers.viz_com.VizCom object at 0x0000025C43699F28>
>   File "c:\users\roba7\anaconda3\lib\site-packages\manga_py\providers\viz_com.py", line 93, in prepare_cookies
>     self.auth()
>     │    └ <bound method VizCom.auth of <manga_py.providers.viz_com.VizCom object at 0x0000025C43699F28>>
>     └ <manga_py.providers.viz_com.VizCom object at 0x0000025C43699F28>
>   File "c:\users\roba7\anaconda3\lib\site-packages\manga_py\providers\viz_com.py", line 127, in auth
>     self.__cookies['remember_token'] = remember['trust_user_id_token_web']
>     │                                  └ {'ok': 1}
>     └ <manga_py.providers.viz_com.VizCom object at 0x0000025C43699F28>
> 
> KeyError: 'trust_user_id_token_web'
>

**Comment by 1271** [comment]
Ohh...
The site changed the storage of cookies.

Please do the same with the version `pip install manga-py==1.8.5rc1`

**Comment by 1271** [comment]
@mugenZebra 
There is no connection with you.
If your problem is resolved, please close issue.
If not, I'm still waiting for an answer.

**Comment by thegreatestminer** [comment]
Doesn't work anymore.

```
moot@7c09751204d7:~/manga-py# python3 manga.py https://www.viz.com/shonenjump/chainsaw-man-chapter-1/chapter/17489
Provider not found
Please check if your inputed domain is supported by manga-py:
- https://manga-py.com/manga-py/#resources-list
- https://manga-py.github.io/manga-py/#resources-list (alternative)
- https://yuru-yuri.github.io/manga-py/ (deprecated)
Make sure that your inputed URL is correct

Trace:
  File "/root/manga-py/manga_py/__init__.py", line 43, in _init_cli
    cli_mode.start()
  File "/root/manga-py/manga_py/cli/__init__.py", line 43, in start
    raise e
  File "/root/manga-py/manga_py/cli/__init__.py", line 34, in start
    info=self._info,
  File "/root/manga-py/manga_py/parser.py", line 35, in init_provider
    raise AttributeError('Provider not found')
```

**Comment by 1271** [comment]
Hey. I will try to check it
Unfortunately, from my country there is no access to this section.
