### ISSUE TITLE
Bug: hatigarmscans.net

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#186]
# Bug report
Environment:

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.5.6.1
URL | `http://hatigarmscans.net/manga/seirei-tachi-no-rakuen-to-risou-no-isekai-seikatsu`

#### To Reproduce:
~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp --show-current-chapter-info --destination Manga/ http://hatigarmscans.net/manga/seirei-tachi-no-rakuen-to-risou-no-isekai-seikatsu
~~~

#### Additional context
Log:
~~~
2019-06-04 10:08:41.020 | ERROR    | manga_py.cli:start:41 - An error has been caught in function 'start', process 'MainProcess' (10455), thread 'MainThread' (140187667023616):
Traceback (most recent call last):

  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/bin/manga-py", line 10, in <module>
    sys.exit(main())
    │   │    └ <function main at 0x7f7ffa4a10d0>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/__init__.py", line 92, in main
    code, _info = _run_util(args)
                  │         └ ArgumentParser(prog='manga-py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler...
                  └ <function _run_util at 0x7f7ffa48fea0>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/__init__.py", line 51, in _run_util
    code = _init_cli(args, _info)
           │         │     └ <manga_py.info.Info object at 0x7f7ffa4a4748>
           │         └ ArgumentParser(prog='manga-py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler...
           └ <function _init_cli at 0x7f7ffa48fe18>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/__init__.py", line 39, in _init_cli
    cli_mode.start()
    │        └ <bound method Cli.start of <manga_py.cli.Cli object at 0x7f7ffa4a46a0>>
    └ <manga_py.cli.Cli object at 0x7f7ffa4a46a0>
> File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/cli/__init__.py", line 41, in start
    self.parser.start()
    │    │      └ <bound method Parser.start of <manga_py.parser.Parser object at 0x7f7ffa4a4710>>
    │    └ <manga_py.parser.Parser object at 0x7f7ffa4a4710>
    └ <manga_py.cli.Cli object at 0x7f7ffa4a46a0>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/parser.py", line 45, in start
    self.provider.process(self.params['url'], self.params)
    │    │        │       │    │              │    └ {'reverse_downloading': False, 'one_thread': False, 'show_current_chapter_info': True, 'no_multi_threads': False, 'not_change_fi...
    │    │        │       │    │              └ <manga_py.parser.Parser object at 0x7f7ffa4a4710>
    │    │        │       │    └ {'reverse_downloading': False, 'one_thread': False, 'show_current_chapter_info': True, 'no_multi_threads': False, 'not_change_fi...
    │    │        │       └ <manga_py.parser.Parser object at 0x7f7ffa4a4710>
    │    │        └ <bound method Provider.process of <manga_py.providers.hatigarmscans_eu.HatigarmScansEu object at 0x7f7ffa4a4978>>
    │    └ <manga_py.providers.hatigarmscans_eu.HatigarmScansEu object at 0x7f7ffa4a4978>
    └ <manga_py.parser.Parser object at 0x7f7ffa4a4710>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/provider.py", line 83, in process
    self.loop_chapters()
    │    └ <bound method Provider.loop_chapters of <manga_py.providers.hatigarmscans_eu.HatigarmScansEu object at 0x7f7ffa4a4978>>
    └ <manga_py.providers.hatigarmscans_eu.HatigarmScansEu object at 0x7f7ffa4a4978>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/provider.py", line 114, in loop_chapters
    self._info.add_volume(self.chapter_for_json(), self.get_archive_path())
    │    │     │          │    │                   │    └ <bound method Provider.get_archive_path of <manga_py.providers.hatigarmscans_eu.HatigarmScansEu object at 0x7f7ffa4a4978>>
    │    │     │          │    │                   └ <manga_py.providers.hatigarmscans_eu.HatigarmScansEu object at 0x7f7ffa4a4978>
    │    │     │          │    └ <bound method Base.chapter_for_json of <manga_py.providers.hatigarmscans_eu.HatigarmScansEu object at 0x7f7ffa4a4978>>
    │    │     │          └ <manga_py.providers.hatigarmscans_eu.HatigarmScansEu object at 0x7f7ffa4a4978>
    │    │     └ <bound method Info.add_volume of <manga_py.info.Info object at 0x7f7ffa4a4748>>
    │    └ <manga_py.info.Info object at 0x7f7ffa4a4748>
    └ <manga_py.providers.hatigarmscans_eu.HatigarmScansEu object at 0x7f7ffa4a4978>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/provider.py", line 163, in get_archive_path
    _path = remove_file_query_params(self.get_archive_name())
            │                        │    └ <bound method Std.get_archive_name of <manga_py.providers.hatigarmscans_eu.HatigarmScansEu object at 0x7f7ffa4a4978>>
            │                        └ <manga_py.providers.hatigarmscans_eu.HatigarmScansEu object at 0x7f7ffa4a4978>
            └ <function remove_file_query_params at 0x7f7ffa48a158>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/providers/helpers/std.py", line 5, in get_archive_name
    idx = self.get_chapter_index()
          │    └ <bound method HatigarmScansEu.get_chapter_index of <manga_py.providers.hatigarmscans_eu.HatigarmScansEu object at 0x7f7ffa4a4978...
          └ <manga_py.providers.hatigarmscans_eu.HatigarmScansEu object at 0x7f7ffa4a4978>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/providers/hatigarmscans_eu.py", line 12, in get_chapter_index
    group = self.re.search(index_re, url).group(1)
            │    │  │      │         └ 'http://hatigarmscans.net/manga/seirei-tachi-no-rakuen-to-risou-no-isekai-seikatsu/chapter-1'
            │    │  │      └ '/manga/[^/]+/(\\d+(?:\\.\\d+)?)'
            │    │  └ <function search at 0x7f7ffa8bad90>
            │    └ <module 're' from '~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/re.py'>
            └ <manga_py.providers.hatigarmscans_eu.HatigarmScansEu object at 0x7f7ffa4a4978>

AttributeError: 'NoneType' object has no attribute 'group'
~~~

**Comment by 1271** [comment]
Please, check new version

**Comment by gromenauer** [comment]
Works OK :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.6.0
URL | `http://hatigarmscans.net/manga/seirei-tachi-no-rakuen-to-risou-no-isekai-seikatsu`
