### ISSUE TITLE
--print-json bug

### ISSUE THREAD

**Issue by 1271** [yuru-yuri/manga-dl#60]
https://github.com/yuru-yuri/manga-dl/issues/30#issuecomment-399362454

```bash
Traceback (most recent call last):
  File "manga.py", line 12, in <module>
    main()
  File "~/PycharmProjects/Manga-Downloader/manga_py/__init__.py", line 66, in main
    print(dumps(_info.get()))
  File "~/anaconda3/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "~/anaconda3/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "~/anaconda3/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "~/anaconda3/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
```

**Comment by 1271** [comment]
This error is due to the peculiarity of some providers. They do not require a list of chapters.
I completely forgot about it when I did --print-json.

This is indeed a big mistake.
In the near future, this will be fixed.

Wait for version 1.3.0, please.

**Comment by 1271** [comment]
Worked now.
