### ISSUE TITLE
Error installing manga_py-1.3.1.0

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#65]
~~~ bash
# New virtualenv with pipenv shell.
pip freeze
# Nothing here
python --version
# Python 3.5.2
pip install manga-py --upgrade --no-cache-dir
~~~
~~~
Collecting manga-py
  Downloading https://files.pythonhosted.org/packages/c3/f3/5fcfdd0016acb85aa0699a2fab3a33ed85875d31ed4809e92542fc97382c/manga_py-1.3.1.0.tar.gz (80kB)
    100% |████████████████████████████████| 81kB 1.6MB/s 
    Complete output from command python setup.py egg_info:
    No module named 'manga_py.cli'
    Setup in progress?
    Traceback (most recent call last):
      File "/tmp/pip-install-1gzi6naj/manga-py/manga_py/__init__.py", line 10, in <module>
        from .cli import Cli, check_version
    ImportError: No module named 'manga_py.cli'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-1gzi6naj/manga-py/setup.py", line 4, in <module>
        from manga_py.meta import __version__, __downloader_uri__
      File "/tmp/pip-install-1gzi6naj/manga-py/manga_py/__init__.py", line 19, in <module>
        print('manga-py version: %s' % __version__, file=stderr)
    NameError: name '__version__' is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-1gzi6naj/manga-py/
~~~

**Comment by gromenauer** [comment]
Installing `manga-py` fails in strange ways.
Tried, in chronological order (empty = fail) to install `manga-py` version :
* [ ] 1.3.1.0
* [ ] 1.2.2.3
* [ ] 1.2.2.2
* [ ] 1.2.2.1
* [ ] 1.2.2.0
* [ ] 1.2.0.5
* [x] 1.1.0
* [x] 1.1.1
* [x] 1.1.4
* [x] 1.2.0.1
* [x] 1.2.1.0
* [ ] 1.3.1.0
* [x] 1.2.2.0
* [x] 1.2.2.1
* [x] 1.0.1
* [x] 1.0.1.1
* [x] 1.0.1.2
* [x] 1.0.2
* [x] 1.0.3
* [x] 1.0.4
* [x] 1.0.4.1
* [x] 1.0.5
* [x] 1.1.0
* [x] 1.1.1
* [x] 1.1.2
* [x] 1.1.3
* [x] 1.1.4
* [x] 1.2.0.1
* [x] 1.2.0.2
* [x] 1.2.0.3
* [x] 1.2.0.4
* [x] 1.2.0.5
* [x] 1.2.1.0
* [x] 1.2.1.1
* [x] 1.2.1.3
* [x] 1.2.1.4
* [x] 1.2.2.0
* [x] 1.2.2.1
* [x] 1.2.2.2
* [x] 1.2.2.3
* [ ] 1.3.0a0
* [ ] 1.3.0.1a0
* [ ] 1.3.0.2a0
* [ ] 1.3.0.3a0
* [ ] 1.3.1.0

**Comment by gromenauer** [comment]
Please, try to install it in a new virtualenv.

**Comment by 1271** [comment]
Oh .. I'm a fool.
Thank you!

Fixed for version >=[1.3.1.1](https://github.com/yuru-yuri/manga-dl/releases/tag/1.3.1.1)

Update to the latest version:
```
pip install manga-py -U --no-cache-dir
```

**Comment by gromenauer** [comment]
Installs ok. But something is broken :/
~~~
manga-py --help
~~~
~~~
Setup in progress?
Traceback (most recent call last):
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/bin/manga-py", line 11, in <module>
    sys.exit(main())
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/__init__.py", line 87, in main
    if __version__.find('alpha'):
NameError: name '__version__' is not defined
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/__init__.py", line 31, in before_shutdown
    temp_dir = get_temp_path()
NameError: name 'get_temp_path' is not defined
~~~

**Comment by 1271** [comment]
Excuse me. My work takes almost all of the time. Sometimes I make mistakes in manga-py.
One moment.

**Comment by 1271** [comment]
Looks like I'm quite overheated in the sun.
I fixed it. Thanks for the issue!

Use `pip install manga-py==1.3.1.2` for update

**Comment by gromenauer** [comment]
~~~
manga-py --version
Alpha release! There may be errors!
1.3.1.2
~~~
Sorry, bad news:
~~~ bash
manga-py --cbz --zero-fill --rename-pages --destination Manga/ http://www.mangatown.com/manga/takarakuji_de_40_oku_atattandakedo_isekai_ni_ijuu_suru/
~~~
~~~
Alpha release! There may be errors!
Traceback (most recent call last):
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/bin/manga-py", line 11, in <module>
    sys.exit(main())
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/__init__.py", line 91, in main
    if parse_args.update_all:
AttributeError: 'Namespace' object has no attribute 'update_all'
~~~

It happened to me too, this days with no time and the code gets stubborn.

**Comment by gromenauer** [comment]
Tried to shortcut it with 
~~~ diff
- if parse_args.update_all:
+ if False:
~~~
and got: 
~~~
Traceback (most recent call last):
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/bin/manga-py", line 11, in <module>
    sys.exit(main())
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/__init__.py", line 94, in main
    code, _info = _run_util(args)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/__init__.py", line 55, in _run_util
    code = _init_cli(args, _info)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/__init__.py", line 32, in _init_cli
    if args.parse_args().full_error:
AttributeError: 'Namespace' object has no attribute 'full_error'
~~~

**Comment by 1271** [comment]
Ohhh.... One moment!
I completely forgot that I deleted this.

Please, check version 1.3.1.3

**Comment by 1271** [comment]
Check version 1.3.1.4

**Comment by 1271** [comment]
If the problem is not up to date, please close this issue.
Thank you

**Comment by gromenauer** [comment]
Installs fine
